config/routes.rb
Rails.application.routes.draw do
  get 'bookcomments/show'

  get 'userparams/new'

  get 'userparams/show'

  get 'userparams/edit'

  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  resources :books do
    resources :comments
  end
  resources :userparams


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	 has_attached_file :image, styles: { medium: "300x300>", thumb: "150x150>" }
	 validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	belongs_to :user

	mount_uploaders :libraries, LibraryUploader


  serialize :libraries, JSON # If you use SQLite, add this line.
  validates :name,:body,:libraries,:image, presence: true
  validates :name, length: 4..256
  validates :body, length: 8..256


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :books
         has_one :userparam
         has_many :book_comments
end

app/models/userparam.rb
class Userparam < ApplicationRecord
	belongs_to :user
	validates :name, :surname, :age, presence: true
	validates :name, :surname, length: 2..36
	validates :age, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user! 
  before_action :find_book, only: [:show, :edit, :update, :destroy]

 def index
  	@books = Book.all
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = current_user.books.build(book_params)
    if @book.save
      redirect_to root_path
    else render 'new'
   
    end  
  end
  
  def show
    

  end
  
  def edit
  end
  
  def update
    if @book.update(book_params)
     
      redirect_to book_path(@book.id)
    else render 'edit'
   
    end
    
  end
  
  def destroy
    @book.destroy
    redirect_to root_path
  end
  
private

  def book_params
    params.require(:book).permit(:user_id, :name, :body, :image, {libraries: []})
  end
  
  def find_book
    @book = Book.find_by(id: params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  	@books = Book.all
  end
end

app/controllers/userparams_controller.rb
class UserparamsController < ApplicationController
  before_action :authenticate_user!

  def new
    @userparam = Userparam.new
  end

  def create
    @userparam = current_user.build_userparam(profile_params)
    if @userparam.save
      redirect_to userparam_path(@userparam.id)
    else render 'new'
    end

  end

  def show
  end

  def edit
    @userparam = current_user.userparam
  end

  def update
    @userparam = Userparam.find_by(user_id: current_user.id)
    if @userparam.update(profile_params)
       redirect_to userparam_path(@userparam.id)
    else render 'edit'
    end

  end

private

  def profile_params
    params.require(:userparam).permit(:user_id, :name, :surname, :age)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userparams_helper.rb
module UserparamsHelper
end

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
 
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @book, url: book_path(@book.id) do |f| %>

<%= f.file_field :image %><br><br>


  <%= f.text_field :name %><br />
  <%= f.text_area :body, size: "60x12" %><br />
  <%= f.file_field :libraries, multiple: true %><br><br>
  <%= f.submit "Update" %>
<% end %>

app/views/books/new.html.erb
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>
 
    <ul>
    <% @book.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @book, url: books_path do |f| %>


  <%= f.file_field :image %><br />
  <%= f.text_field :name %><br />
  <%= f.text_area :body, size: "60x12" %><br />
  <%= f.file_field :libraries, multiple: true %><br><br>
  <%= f.submit "Create" %>
<% end %>

app/views/books/show.html.erb
<Center><h3>User: <%= @book.user.email %><br />
Name: <%= @book.name %><br />
Body: <%= @book.body %><br />
<%=image_tag@book.image.url(:medium) %><br />

<% @book.libraries.each do |b| %>

  <%= link_to "Download", b.url %>
<% end %>
<% if @book.user_id == current_user.id %>
<p><%= link_to "edit", edit_book_path(@book.id) %> |
<%= link_to "delete", book_path(@book.id), method: :delete %><br /></p>
<% end %></h3></Center>

app/views/layouts/_navbar.html.erb
<% if user_signed_in? %>
 <h3> <%= link_to "Home", root_path %> 
  <%= link_to "New Book", new_book_path %></h3> 
  
   <% if current_user.userparam.nil? %>
  
   <h3><%= link_to "Profile", new_userparam_path %></h3>
  <% else %>
  <h3> <%= link_to "Profile", userparam_path(current_user.id) %> </h3>
  <% end %>


 <h2 align="right"><%= link_to "Logout",  destroy_user_session_path, method: :delete %> </h2>
<% else %>
   <%= link_to "Login", new_user_session_path %> |
   <%=link_to "Registration", new_user_registration_path%> |
  
   

  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Libr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<% if @books == [] %>
    <p>Create new book</p>
<% else %>
    <% @books.each do |book| %>
       
       <CENTER><h3>	<p>User
	    
       	<b><%= book.user.email %></b> write: <br />
	  <p><b> <%=image_tag book.image.url(:medium) %><br /></b>	
       <b><%= book.name %></b><br />
       <%= book.body %></p>
       <p><%= link_to "Read More", book_path(book.id) %></p></h3>
       </CENTER>
    <% end %>
<% end %>

app/views/userparams/edit.html.erb
<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this userparam from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @userparam, url: userparam_path(current_user.id) do |f| %>

  Name: <%= f.text_field :name %><br />
  Surname: <%= f.text_field :surname %><br />
  Age: <%= f.text_field :age %><br />
  

  <%= f.submit "Update" %>
<% end %>

app/views/userparams/new.html.erb
<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this userparam from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_for @userparam, url: userparams_path do |f| %>

<% if @userparam.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@userparam.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @userparam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  <p>Name: <%= f.text_field :name %><br /></p>
  Surname: <%= f.text_field :surname %><br />
  Age: <%= f.text_field :age %><br />
  <%= f.submit "Create" %>
<% end %>

app/views/userparams/show.html.erb
<h3>Name: <%= current_user.userparam.name %><br />
Surname: <%= current_user.userparam.surname %><br />
Age: <%= current_user.userparam.age %><br />
<%= link_to "Edit", edit_userparam_path(current_user.id) %><br />
<%= link_to "Edit Password", edit_user_registration_path(current_user.id) %><br /></h3>